services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9443:9443"   # HTTPS
      - "8000:8000"   # для агентов (опционально)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    environment:
      - PORTAINER_ADMIN_PASSWORD=${PORTAINER_ADMIN_PASSWORD}

volumes:
  portainer_data: